name: Build RustDesk Ultimate

on:
  workflow_dispatch:
    inputs:
      os:
        required: true
        type: choice
        options:
        - windows
        - linux
      version:
        required: true
      api_server:
        required: true
      id_server:
        required: true
      relay_server:
        required: false
      key:
        required: true
      custom_id:
        required: false
      password:
        required: false
      hide_tray:
        required: false
        type: string
        default: 'true'
      auto_update_check:
        required: false
        type: string
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # æ›´æ–° checkout åˆ° v4
      - uses: actions/checkout@v4
      
      - name: Setup Python
        # æ›´æ–° setup-python åˆ° v5
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install deps
        run: pip install requests
        
      - name: Generate Package
        env:
          OS_TARGET: ${{ inputs.os }}
          VERSION: ${{ inputs.version }}
          API_SERVER: ${{ inputs.api_server }}
          ID_SERVER: ${{ inputs.id_server }}
          RELAY_SERVER: ${{ inputs.relay_server }}
          KEY: ${{ inputs.key }}
          CUSTOM_ID: ${{ inputs.custom_id }}
          PASSWORD: ${{ inputs.password }}
          HIDE_TRAY: ${{ inputs.hide_tray }}
          AUTO_UPDATE_CHECK: ${{ inputs.auto_update_check }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          python scripts/builder.py
          echo "FILE=$(cat artifact_* | cut -d'=' -f2)" >> $GITHUB_ENV
          
      - name: Upload
        # ğŸš‘ æ ¸å¿ƒä¿®å¤ï¼šå¿…é¡»ä½¿ç”¨ v4ï¼Œå¦åˆ™è¢«GitHubæ‹¦æˆª
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-custom
          path: ${{ env.FILE }}
          retention-days: 2
